import type { Metadata } from "next";
import "@styles/tailwind.css";
import ClientGate from "@/features/auth/components/client-gate";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientGate>{children}</ClientGate>
      </body>
    </html>
  );
}
